# Generated by Django 5.1.1 on 2024-09-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Em andamento'), ('DONE', 'Concluída'), ('CANCELLED', 'Cancelada'),
                                            ('BLOCKED', 'Bloqueada'), ('BACKLOG', 'Backlog')], default='TODO',
                                   max_length=20),
        ),
    ]
